config/routes.rb
Rails.application.routes.draw do

  resources :blogs, only: [:show, :index]
  resources :comments, only: [:index, :create, :destroy]
  resources :categories, only: [:index]

  root to: 'blogs#index'

  get 'login' => 'home#login'
  get 'auth' => 'home#auth'

  namespace :zero do
    resource :session, only: [:new, :create, :destroy]
    resources :blogs do
      resources :comments
      member do
        post :submit
      end
    end
    resources :comments, only: [:index, :show, :destroy]
    resources :categories
    resources :users, only: [:index, :destroy]
    delete 'blobs/:signed_id' => 'blobs#destroy'
    root to: 'dashboard#index'
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar  navbar-expand-lg  navbar-dark bg-dark sticky-top" id="nav-header">
  <div class="header">
    <%= link_to 'ZeroHome', root_path, class: 'navbar-brand'%>
    <button class="navbar-toggler navbar-toggler-right bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="icon ion-menu"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav nav ml-auto">
        <li class="nav-item mx-0 mx-lg-1">
          <%= link_to 'Blogs', blogs_path, class: 'nav-link py-3 px-0 px-lg-3 rounded'%>
        </li>
        <li class="nav-item mx-0 mx-lg-1">
          <%= link_to 'About Zero', about_path, class: 'nav-link py-3 px-0 px-lg-3 rounded'%>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ZeroHomepage</title>
  <%= favicon_pack_tag 'favicon.jpg' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_pack_tag "application" %>
</head>
<body>

<%= yield %>
  <div class="footer">
    <%= link_to "苏ICP备2021053771号-1", "https://beian.miit.gov.cn/" %>
  </div>
</body>

</html>
<style type="text/css">
  body {
      position: relative;
  }

  body:after {
      content : "";
      display: block;
      position: fixed;
      top: 0;
      left: 0;
      background-image: url("<%= image_pack_url('bg.jpg')%>");
      background-size: cover;
      width: 100%;
      height: 100%;
      opacity : 0.4;
      z-index: -1;
  }

  .footer{
      width: 100%;
      height: 40px;
      line-height: 40px;
      text-align: center;
      margin: 0px auto;
      position: absolute;

  }
</style>
<!-- <script type="text/javascript">
  loadlive2d("live2d", "models/kaga/model.json");
</script>

<div class="kaga">
  <div class="kaga-tips"></div>
  <canvas id="live2d" width="280" height="250" class="live2d"></canvas>
</div>
 -->

app/views/layouts/zero.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ZeroHomepage</title>
  <%= favicon_pack_tag 'favicon.jpg' %>
  <%= javascript_pack_tag 'zero', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'zero', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="margin: 0">

<div style="display: flex">
  <%= render 'layouts/zero/header'%>
  <div style="flex: 1; padding:25px">
    <div style="min-height: 64px;" ></div>
    <%= yield %>
  </div>
</div>

</body>
</html>